import { useEffect } from "react";
import { FileText } from "lucide-react";
import { Footer } from "@/components/Footer";
import { SiteHeader } from "@/components/SiteHeader";

function SEOHead() {
  useEffect(() => {
    const title = "Terms & Conditions | PodRise";
    const desc = "Read PodRise's terms and conditions. Understand the rules and guidelines for using our podcast summaries and intelligence platform.";
    document.title = title;
    const setMeta = (attr: string, key: string, value: string) => {
      let el = document.querySelector(`meta[${attr}="${key}"]`) as HTMLMetaElement | null;
      if (!el) { el = document.createElement("meta"); el.setAttribute(attr, key); document.head.appendChild(el); }
      el.setAttribute("content", value);
    };
    setMeta("name", "description", desc);
    setMeta("property", "og:title", title);
    setMeta("property", "og:description", desc);
    setMeta("name", "twitter:card", "summary");
    setMeta("name", "twitter:title", title);
    setMeta("name", "twitter:description", desc);
  }, []);
  return null;
}

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <SEOHead />
      <SiteHeader />

      <main className="flex-1 w-full max-w-3xl mx-auto px-6 py-10">
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2.5 px-6 py-2.5 rounded-full bg-primary/[0.07] text-primary text-base sm:text-lg font-display font-bold uppercase tracking-widest mb-4">
            <FileText className="w-5 h-5" />
            Terms & Conditions
          </div>
          <h1 className="sr-only">Terms & Conditions</h1>
          <p className="text-base text-[#52525B] dark:text-[#A1A1AA] dark:text-muted-foreground">Last updated: March 14, 2026</p>
        </div>

        <div className="prose prose-sm max-w-none space-y-6 text-[#52525B] dark:text-[#A1A1AA]">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">1. Acceptance of Terms</h2>
            <p>By accessing or using PodRise ("the Service"), operated at podrise.com, you agree to be bound by these Terms and Conditions ("Terms"). If you do not agree to these Terms, you may not access or use the Service. These Terms constitute a legally binding agreement between you and PodRise ("we," "our," or "us").</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">2. Description of Service</h2>
            <p>PodRise provides AI-generated daily summaries of podcast episodes delivered via email. The Service allows users to select podcasts, receive automated recaps, and manage their preferences through a web-based dashboard.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">3. User Accounts</h2>
            <p>To use the Service, you must create an account by providing a valid email address. You are responsible for maintaining the confidentiality of your account and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">4. Service Plans</h2>
            <p>PodRise is free to use. All features are available to all users at no cost. Features and availability are subject to change at our discretion.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to any part of the Service</li>
              <li>Interfere with or disrupt the Service or servers connected to the Service</li>
              <li>Use automated systems or software to extract data from the Service (scraping)</li>
              <li>Reproduce, distribute, or create derivative works from our content without permission</li>
              <li>Impersonate any person or entity or misrepresent your affiliation</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">7. Intellectual Property</h2>
            <p>The Service, including its design, features, and content generated by PodRise, is protected by copyright, trademark, and other intellectual property laws. AI-generated podcast summaries are provided for personal, non-commercial use only. The original podcast content remains the property of its respective creators and rights holders.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">8. Advertising and Sponsored Content</h2>
            <p>The Service may include advertisements, sponsored content, and promotional materials from third-party advertisers within emails, on the website, and in any audio or video content we produce. By using the Service, you acknowledge and agree that:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>We may display advertisements and sponsored content within your daily podcast recap emails and other communications from PodRise</li>
              <li>Advertisements may be targeted based on non-personally-identifiable information, including but not limited to your selected podcast preferences, indicated industries, professional roles, and general interest categories</li>
              <li>We do not share your personal information (such as your name or email address) with advertisers. Targeting is based solely on aggregated, non-identifiable audience segments</li>
              <li>We are not responsible for the content, accuracy, or practices of third-party advertisers. Interactions with advertisers, including purchases, are solely between you and the advertiser</li>
              <li>Sponsored content will be clearly labeled or distinguished from editorial content</li>
              <li>We may include advertisements in any podcasts, audio content, or video content we produce in the future</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">9. Disclaimer of Warranties</h2>
            <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. We do not warrant that the Service will be uninterrupted, error-free, or secure. AI-generated summaries may contain inaccuracies and should not be relied upon as a substitute for listening to the original podcast episodes.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">10. Limitation of Liability</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL PODRISE, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES RESULTING FROM YOUR USE OF THE SERVICE.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">11. Indemnification</h2>
            <p>You agree to indemnify, defend, and hold harmless PodRise and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses, including reasonable attorney's fees, arising out of or in any way connected with your access to or use of the Service or your violation of these Terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">12. Termination</h2>
            <p>We reserve the right to suspend or terminate your account and access to the Service at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties, or for any other reason. Upon termination, your right to use the Service will immediately cease.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">13. Governing Law</h2>
            <p>These Terms shall be governed by and construed in accordance with the laws of the United States, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be resolved in the courts of competent jurisdiction.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">14. Changes to Terms</h2>
            <p>We reserve the right to modify these Terms at any time. We will notify you of material changes by posting the updated Terms on this page and updating the "Last updated" date. Your continued use of the Service after any changes constitutes your acceptance of the revised Terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">15. Contact Us</h2>
            <p>If you have any questions about these Terms, please <a href="/contact" className="text-primary hover:underline">contact us</a>.</p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
