export const SEED_CATEGORIES = [
  {
    name: "Business",
    slug: "business",
    description: "The best business podcasts covering entrepreneurship, leadership, marketing, strategy, and more.",
    icon: "briefcase",
    keywords: ["business", "entrepreneurship", "startup", "saas", "management", "strategy", "acquisitions", "growth", "marketing", "online marketing", "side hustles", "company analysis", "business of tech", "organizational", "coaching", "lifestyle"],
    sortOrder: 1,
  },
  {
    name: "Technology",
    slug: "technology",
    description: "Top technology podcasts covering AI, software engineering, product management, and emerging tech.",
    icon: "cpu",
    keywords: ["tech", "ai", "software", "engineering", "product management", "automotive", "consumer tech", "internet culture", "venture capital / software", "apple", "true crime"],
    sortOrder: 2,
  },
  {
    name: "Finance",
    slug: "finance",
    description: "Leading finance podcasts on investing, personal finance, markets, and wealth building.",
    icon: "dollar-sign",
    keywords: ["finance", "investing", "markets", "wealth", "personal finance", "financial independence", "consumer advice", "money", "economics", "economic", "crypto"],
    sortOrder: 3,
  },
  {
    name: "Health",
    slug: "health",
    description: "Top health podcasts exploring longevity, fitness, mental health, and science-backed wellness.",
    icon: "heart",
    keywords: ["health", "fitness", "medicine", "longevity", "functional medicine", "performance science", "nutrition"],
    sortOrder: 4,
  },
  {
    name: "Self-Improvement",
    slug: "self-improvement",
    description: "Podcasts for personal growth - productivity, mindfulness, motivation, and career development.",
    icon: "zap",
    keywords: ["self-improvement", "personal development", "motivation", "mindset", "empowerment", "productivity", "philosophy / self-improvement", "coaching"],
    sortOrder: 5,
  },
  {
    name: "Society & Culture",
    slug: "society-culture",
    description: "Podcasts exploring interviews, comedy, storytelling, and the human experience.",
    icon: "users",
    keywords: ["society", "culture", "interviews", "comedy", "human stories", "narrative", "entertainment", "film", "tv", "arts", "sports", "relationships", "design"],
    sortOrder: 6,
  },
  {
    name: "News & Politics",
    slug: "news",
    description: "Stay informed with the best news and politics podcasts covering daily briefings and analysis.",
    icon: "globe",
    keywords: ["news", "politics", "law", "government", "daily", "international", "media", "weekly"],
    sortOrder: 7,
  },
  {
    name: "Education",
    slug: "education",
    description: "Educational podcasts covering history, philosophy, science, and big ideas.",
    icon: "book-open",
    keywords: ["education", "history", "language", "debates", "big ideas", "general knowledge", "philosophy / education", "philosophy / science"],
    sortOrder: 8,
  },
  {
    name: "Psychology",
    slug: "psychology",
    description: "Psychology podcasts exploring human behavior, cognitive science, and the mind.",
    icon: "brain",
    keywords: ["psychology", "behavior", "mental health", "wellbeing", "cognitive"],
    sortOrder: 9,
  },
  {
    name: "Science",
    slug: "science",
    description: "Science podcasts covering space, biology, physics, and the natural world.",
    icon: "flask-conical",
    keywords: ["science", "space", "fact-checking"],
    sortOrder: 10,
  },
];
