export const SEED_LISTS = [
  {
    name: "Artificial Intelligence",
    slug: "artificial-intelligence",
    description: "Podcasts covering AI, machine learning, and the future of intelligent systems",
    podcastSlugs: ["cognitiverevolution","eyeonai","ai-breakdown","ai-for-humans","aidailybrief","last-week-in-ai","latentspace","gradient-dissent","machine-learning-street-talk","twimlai","superdatascience-podcast","data-exchange-podcast","lexfridman","hardfork","driverlessdigest"],
    category: "industry",
    sortOrder: 1,
  },
  {
    name: "Venture Capital",
    slug: "venture-capital",
    description: "Inside the world of startup funding, VC strategy, and deal-making",
    podcastSlugs: ["twentyminutevc","acquired","allin","equity","myfirstmillion","thisweekinstartups","y-combinator-podcast","a16z","capitalallocators","logan-bartlett-show","bg2pod","compound-insights"],
    category: "industry",
    sortOrder: 2,
  },
  {
    name: "SaaS & Software",
    slug: "saas",
    description: "Software-as-a-service strategy, engineering, and product",
    podcastSlugs: ["lennys","build-with-maggie-crowley","product-thinking","software-engineering-daily","moderncto","changelog","dotnetrocks","latentspace","startupsfortherestofus","bootstrapped-founder","indie-hackers-podcast","saastr"],
    category: "industry",
    sortOrder: 3,
  },
  {
    name: "Defense Tech",
    slug: "defense-tech",
    description: "Defense technology, national security, and geopolitical strategy",
    podcastSlugs: ["joelonsdale","allin","dwarkesh","future-of-life-institute-podcast","lexfridman","ezraklein"],
    category: "industry",
    sortOrder: 4,
  },
  {
    name: "Climate & Energy",
    slug: "climate-energy",
    description: "Clean energy, sustainability, and climate technology",
    podcastSlugs: ["exponential-view-with-azeem-azhar","freakonomics","econtalk","ezraklein","in-our-time","99-invisible"],
    category: "industry",
    sortOrder: 5,
  },
  {
    name: "Crypto & Web3",
    slug: "crypto-web3",
    description: "Cryptocurrency, blockchain, DeFi, and decentralized technology",
    podcastSlugs: ["bankless","unchained","allin","a16z","myfirstmillion"],
    category: "industry",
    sortOrder: 6,
  },
  {
    name: "Robotics & Hardware",
    slug: "robotics",
    description: "Robotics, autonomous systems, and hardware innovation",
    podcastSlugs: ["driverlessdigest","cognitiverevolution","lexfridman","exponential-view-with-azeem-azhar","a16z","joelonsdale"],
    category: "industry",
    sortOrder: 7,
  },
  {
    name: "Technology",
    slug: "technology",
    description: "Broad tech coverage from consumer electronics to big tech strategy",
    podcastSlugs: ["hardfork","decoder","thevergecast","waveform","techmemeridehome","bigtechnology","marketplace-tech","bloomberg-technology","accidental-tech-podcast","exponent","land-of-the-giants","pivot"],
    category: "industry",
    sortOrder: 8,
  },
  {
    name: "Media & Content",
    slug: "media-content",
    description: "Media, entertainment, content creation, and the creator economy",
    podcastSlugs: ["thebigpicture","therewatchables","decoder","waveform","garyvee","amyporterfield","influencer-podcast","social-media-marketing-podcast","social-proof","dtc-podcast","smartless","conanobrien"],
    category: "industry",
    sortOrder: 9,
  },
  {
    name: "Economics",
    slug: "economics",
    description: "Economic theory, policy, market analysis, and macro trends",
    podcastSlugs: ["econtalk","freakonomics","macro-musings","planet-money","theindicator","slate-money","economist-podcasts","checks-and-balance","unhedged","marketplace-tech","moneyfortherestofus"],
    category: "industry",
    sortOrder: 10,
  },
  {
    name: "Open Source & Developer",
    slug: "open-source",
    description: "Open source software, developer culture, and engineering practices",
    podcastSlugs: ["changelog","software-engineering-daily","latentspace","moderncto","dotnetrocks","accidental-tech-podcast","indie-hackers-podcast"],
    category: "industry",
    sortOrder: 11,
  },
  {
    name: "Real Estate",
    slug: "real-estate",
    description: "Real estate investing, property management, and market trends",
    podcastSlugs: ["biggerpockets","affordanything","clarkhoward","ramsey-show","moneywise","navigatingwealth"],
    category: "industry",
    sortOrder: 12,
  },
  {
    name: "Health & Longevity",
    slug: "health-longevity",
    description: "Science-backed health optimization, nutrition, and longevity research",
    podcastSlugs: ["hubermanlab","foundmyfitness","doctorsfarmacy","ultimatehuman","modelhealthshow","peterattia","richroll","tenpercenthappier"],
    category: "interest",
    sortOrder: 1,
  },
  {
    name: "Psychology & Behavior",
    slug: "psychology",
    description: "How the mind works, behavioral science, and human decision-making",
    podcastSlugs: ["hiddenbrain","happinesslab","choiceology-with-katy-milkman","you-are-not-so-smart","tenpercenthappier","makingsense","armchairexpert","gray-area-with-sean-illing"],
    category: "interest",
    sortOrder: 2,
  },
  {
    name: "Productivity",
    slug: "productivity",
    description: "Time management, deep work, systems for getting more done",
    podcastSlugs: ["deepquestions","timferriss","lifecoachschool","melrobbins","high-performance-podcast","ed-mylett-show","success-story","100mba"],
    category: "interest",
    sortOrder: 3,
  },
  {
    name: "Decision Making",
    slug: "decision-making",
    description: "Mental models, strategic thinking, and better decision frameworks",
    podcastSlugs: ["knowledgeproject","freakonomics","hiddenbrain","choiceology-with-katy-milkman","conversationswithtyler","econtalk","you-are-not-so-smart","makingsense"],
    category: "interest",
    sortOrder: 4,
  },
  {
    name: "Creativity",
    slug: "creativity",
    description: "Creative process, storytelling, design, and artistic expression",
    podcastSlugs: ["timferriss","99-invisible","tedtalksdaily","freshair","armchairexpert","diaryofaceo","conanobrien","smartless"],
    category: "interest",
    sortOrder: 5,
  },
  {
    name: "Personal Finance",
    slug: "personal-finance",
    description: "Budgeting, saving, debt management, and financial independence",
    podcastSlugs: ["affordanything","choosefi","clarkhoward","ramsey-show","moneywise","financialaudit","moneyfortherestofus","themoneyguyshow","white-coat-investor-podcast","navigatingwealth"],
    category: "interest",
    sortOrder: 6,
  },
  {
    name: "Geopolitics",
    slug: "geopolitics",
    description: "International relations, global power dynamics, and world affairs",
    podcastSlugs: ["global-news-podcast","intelligence-from-the-economist","therestispolitics","ezraklein","gray-area-with-sean-illing","stay-tuned-with-preet","in-our-time","checks-and-balance"],
    category: "interest",
    sortOrder: 7,
  },
  {
    name: "Peak Performance",
    slug: "peak-performance",
    description: "Elite performance, discipline, and pushing human limits",
    podcastSlugs: ["jockopodcast","hubermanlab","high-performance-podcast","ed-mylett-show","impact-theory","tony-robbins-podcast","richroll","artofmanliness","diaryofaceo"],
    category: "interest",
    sortOrder: 8,
  },
  {
    name: "Self Improvement",
    slug: "self-improvement",
    description: "Personal growth, mindset shifts, and becoming your best self",
    podcastSlugs: ["melrobbins","impact-theory","diaryofaceo","dailystoic","jordanharbinger","jockopodcast","lifecoachschool","tenpercenthappier","artofmanliness","tony-robbins-podcast","ed-mylett-show"],
    category: "interest",
    sortOrder: 9,
  },
  {
    name: "Investing",
    slug: "investing",
    description: "Stock markets, portfolio strategy, and building wealth",
    podcastSlugs: ["investlikethebest","westudybillionaires","invested-with-phil-and-danielle-town","intrinsicvalue","animalspirits","compound-and-friends","motley-fool-money","investtalk","art-of-investing","meb-faber-show","moneyfortherestofus","long-view"],
    category: "interest",
    sortOrder: 10,
  },
  {
    name: "Future of Work",
    slug: "future-of-work",
    description: "How work is evolving with remote, AI, and organizational change",
    podcastSlugs: ["worklife","hbrideacast","mckinsey-podcast","lennys","mastersofscale","entreleadership","atthetable","coachingforleaders","strategy-skills-podcast"],
    category: "interest",
    sortOrder: 11,
  },
  {
    name: "Science & Curiosity",
    slug: "science-curiosity",
    description: "Deep dives into science, the universe, and how things work",
    podcastSlugs: ["startalkradio","infinite-monkey-cage","in-our-time","stuffyoushouldknow","skeptics-guide-to-the-universe","radiolab","99-invisible","lexfridman","foundmyfitness"],
    category: "interest",
    sortOrder: 12,
  },
  {
    name: "News & Current Events",
    slug: "news-current-events",
    description: "Daily news, political analysis, and current affairs",
    podcastSlugs: ["thedaily","up-first","global-news-podcast","nbc-nightly-news","cbs-mornings-on-the-go","today-explained","breaking-points","therestispolitics","abc-world-news-this-week"],
    category: "interest",
    sortOrder: 13,
  },
  {
    name: "True Crime & Security",
    slug: "true-crime-security",
    description: "Cybersecurity, hacking stories, and digital investigations",
    podcastSlugs: ["darknetdiaries","information-411","stay-tuned-with-preet"],
    category: "interest",
    sortOrder: 14,
  },
  {
    name: "Marketing",
    slug: "marketing",
    description: "Marketing strategy, growth tactics, brand building, and acquisition",
    podcastSlugs: ["marketingschool","marketing-against-the-grain","marketing-book-podcast","social-media-marketing-podcast","social-proof","dtc-podcast","garyvee","amyporterfield","influencer-podcast","goal-digger","empowerher","mind-your-business-podcast"],
    category: "role",
    sortOrder: 1,
  },
  {
    name: "Sales",
    slug: "sales",
    description: "Sales methodology, closing deals, and revenue growth",
    podcastSlugs: ["salesgravy","alexhormozi","jordanharbinger","youngandprofiting","valuetainment","entreleadership","negotiation-podcast","ed-mylett-show"],
    category: "role",
    sortOrder: 2,
  },
  {
    name: "Founders & CEOs",
    slug: "founders-ceos",
    description: "Lessons from company builders, founder stories, and executive leadership",
    podcastSlugs: ["howibuiltthis","founders","mastersofscale","acquired","myfirstmillion","entrepreneursonfire","mixergy","lean-startup-podcast","diaryofaceo","alexhormozi","joerogan","icedcoffeehour","startup-chat-with-steli-and-hiten","thisweekinstartups","tropicalmba"],
    category: "role",
    sortOrder: 3,
  },
  {
    name: "Product Management",
    slug: "product-management",
    description: "Product strategy, user research, and shipping great products",
    podcastSlugs: ["lennys","build-with-maggie-crowley","product-thinking","hbrideacast","a16z","mastersofscale","exponent"],
    category: "role",
    sortOrder: 4,
  },
  {
    name: "Engineering & Technical",
    slug: "engineering",
    description: "Software engineering, architecture, DevOps, and technical leadership",
    podcastSlugs: ["software-engineering-daily","changelog","latentspace","moderncto","dotnetrocks","accidental-tech-podcast","gradient-dissent","machine-learning-street-talk"],
    category: "role",
    sortOrder: 5,
  },
  {
    name: "Finance & Analysts",
    slug: "finance",
    description: "Financial analysis, markets, and investment professional insights",
    podcastSlugs: ["mastersinbusiness","capitalallocators","investlikethebest","compound-and-friends","motley-fool-money","macro-musings","slate-money","unhedged","meb-faber-show","bloomberg-technology"],
    category: "role",
    sortOrder: 6,
  },
  {
    name: "Leadership & Management",
    slug: "leadership",
    description: "Leadership development, team building, and organizational management",
    podcastSlugs: ["hbrideacast","coachingforleaders","atthetable","daretolead","worklife","entreleadership","learningleader","strategy-skills-podcast","mckinsey-podcast","knowledgeproject","jockopodcast"],
    category: "role",
    sortOrder: 7,
  },
  {
    name: "Entrepreneurs & Side Hustlers",
    slug: "entrepreneurs",
    description: "Entrepreneurship, bootstrapping, side projects, and indie hacking",
    podcastSlugs: ["myfirstmillion","entrepreneursonfire","sidehustleshow","tropicalmba","startupsfortherestofus","bootstrapped-founder","indie-hackers-podcast","acquiringminds","mixergy","icedcoffeehour","skinny-confidential-him-and-her-podcast","wealthyway","bigdeal","100mba"],
    category: "role",
    sortOrder: 8,
  },
  {
    name: "Consultants & Strategists",
    slug: "consultants",
    description: "Consulting, strategy, and professional advisory work",
    podcastSlugs: ["mckinsey-podcast","strategy-skills-podcast","hbrideacast","knowledgeproject","conversationswithtyler","mastersofscale"],
    category: "role",
    sortOrder: 9,
  },
  {
    name: "Data & Analytics",
    slug: "data-analytics",
    description: "Data science, analytics, and data-driven decision making",
    podcastSlugs: ["superdatascience-podcast","data-exchange-podcast","twimlai","gradient-dissent","machine-learning-street-talk","software-engineering-daily"],
    category: "role",
    sortOrder: 10,
  },
  {
    name: "Creators & Influencers",
    slug: "creators",
    description: "Content creation, audience building, and the creator economy",
    podcastSlugs: ["garyvee","amyporterfield","influencer-podcast","social-proof","goal-digger","empowerher","skinny-confidential-him-and-her-podcast","callherdaddy","smartless","conanobrien","waveform"],
    category: "role",
    sortOrder: 11,
  },
];
